##############################################################################
#  Copyright Christopher Kormanyos 2024.
#  Distributed under BSD-3-Clause.

name: elf2uf2
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  elf2uf2-build-native:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: build-and-verify-elf2uf2
        run: |
          echo 'build-and-verify-elf2uf2'
          echo
          make all
          ls -la ./bin/elf2uf2
      - uses: actions/upload-artifact@v4
        with:
          name: elf2uf2-x86_64-linux-gnu
          path: ./bin/elf2uf2
  elf2uf2-build-native-macos:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: build-and-verify-elf2uf2
        run: |
          echo 'build-and-verify-elf2uf2'
          echo
          make all
          ls -la ./bin/elf2uf2
      - uses: actions/upload-artifact@v4
        with:
          name: elf2uf2-macos
          path: ./bin/elf2uf2
  msvc-release-x64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/checkout@v1
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.2
      - name: msvc-release-x64
        shell: cmd
        working-directory: ./
        run: |
          set INCLUDE=%cd%;%INCLUDE%
          MSBuild -m elf2uf2.sln -p:useenv=true -p:Configuration=Release -p:Platform=x64 /t:Rebuild
          dir %cd%\x64\Release\elf2uf2.exe
      - uses: actions/upload-artifact@v4
        with:
          name: elf2uf2-win64-msvc
          path: x64/Release/elf2uf2.exe
